### ISSUE TITLE
setting page font

### ISSUE THREAD

**Issue by rimmesbe** [caustenstehle/prj-rev-bwfs-dasmoto#2]
What you have works for now, but the easiest way to give all your elements a new font is to use inheritance:
html { font-family: Helvetica; }
Now all elements inherit this font. A lot quicker than having to list out every element you want to have the font.

https://github.com/caustenstehle/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/Resources/CSS/style.css#L1-L3

**Comment by caustenstehle** [comment]
Excellent advice - thank you.
