### ISSUE TITLE
use alt attribute

### ISSUE THREAD

**Issue by rimmesbe** [caustenstehle/prj-rev-bwfs-dasmoto#5]
Try to get in the habit of describing your images with the alt attribute. These are used by screen readers and make your code look more professional.

https://github.com/caustenstehle/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L11

**Comment by caustenstehle** [comment]
Thank you! I don't believe that it was covered in the course, but I looked it up, and you are right - it is a good thing to do. Much appreciated.
