### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [caustenstehle/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on the project, looks good. You used some good techniques. I created a few issues for you to take a look at. The changes will help you optimize your code and follow best practice. The biggest thing to work on is organizing your html with divs, creating sections and groups of related elements. This will be important as we get into positioning. Start using dev tools to look at other sites code or even the examples on codecademy just to see how they are structured. Don't really on the examples for the answers though. https://www.codecademy.com/articles/use-devtools

**Comment by caustenstehle** [comment]
Thanks for the input - I appreciate it.
